config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :goals
  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, :goal_id, presence: true

  belongs_to :user
  belongs_to :goal

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :content, :user_id, :exposure, :status, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_token!

  has_many :goals

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil unless user && user.valid_password?(password)
    user
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def ensure_token!
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    session[:session_token] = user.reset_token!
    @current_user = user
  end

  def sign_out
    current_user.reset_token!
    session[:session_token] = nil
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)

    @comment.save!
    flash[:errors] = @comment.errors.full_messages
    redirect_to goal_url(@comment.goal)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to goal_url(@comment.goal)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :goal_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to goals_url
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def index
    @goals = Goal.all.includes(:user)
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to goals_url
  end

  private
  def goal_params
    params.require(:goal).permit(:content, :exposure, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      render :index
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    html = <<-HTML
    <input type="hidden"
    name="authenticity_token"
    value="#{form_authenticity_token}">
    HTML
    html.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h2>Edit Goal</h2>
<form action="<%= goal_url(@goal) %>" method="post">
  <%= auth_token_input %>

  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="goal[status]" value="pending">

  <label>
    Goal
    <input type="textarea" name="goal[content]" value="<%= @goal.content %>">
  </label>

  <label>
    Exposure
    <select name="goal[exposure]" id="Exposure">

      <option value="Public" <%= "selected" if @goal.exposure == "Public" %>>
        Public
      </option>

      <option value="Private"<%= "selected" if @goal.exposure == "Private" %>>
        Private
      </option>

    </select>
  </label>

  <label>Completed
    <input type="checkbox" name="goal[status]" value="completed">
  </label>


  <input type="submit" value="Update goal">
</form>

app/views/goals/index.html.erb
<h2>Goals</h2>
<%= button_to "New goal", new_goal_url %>
<hr>

<ul>
  <% @goals.each do |goal| %>
    <li>
      <% if goal.exposure == "Public" || goal.user_id == current_user.id %>
        <%= goal.content %>
        <%= goal.user.username %>
        <%= goal.status %>
        <%  if goal.user_id == current_user.id %>
          <%= button_to "Edit", edit_goal_url(goal), method: :get %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<br>

app/views/goals/new.html.erb
<h2>New Goal</h2>
<form action="<%= goals_url %>" method="post">
  <%= auth_token_input %>
  
  <input type="hidden" name="goal[status]" value="pending">

  <label>
    Goal
    <input type="textarea" name="goal[content]" value="">
  </label>

  <label>
    Exposure
    <select name="goal[exposure]" id="Exposure">
      <option value="Public">Public</option>
      <option value="Private">Private</option>
    </select>
  </label>

  <input type="submit" value="Make goal">

</form>

app/views/goals/show.html.erb
<h2><%= @goal.user.username %></h2>
<%= @goal.content %>
<%= @goal.status %>
<% if current_user.id == @goal.user_id %>
  <%= link_to "Edit", edit_goal_url(@goal) %>
  <%= button_to "Delete", goal_url(@goal), method: :delete %>
<% end %>

<hr>
Comments
<ul>
  <% @goal.comments.each do |comment| %>
  <li>
    <%= comment.body %>
    <%= comment.user.username %>
  </li>
</ul>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>") if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/errors' %>

 <% if current_user %>
    <%= current_user.username %>
    <%= button_to "Sign out", session_url, method: :delete %>
 <% else %>

 <% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/new.html.erb
<h2>Sign up</h2>
<form action="<%= users_url %>" method="post">
  <%= auth_token_input %>

  <label>username
    <input type="text" name="user[username]" value="">
  </label>

  <label>password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign up">
</form>